/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela.livro;

import dao.AssuntoDAO;
import dao.AutorDAO;
import dao.ClassLiterariaDAO;
import dao.ColecaoDAO;
import dao.EditoraDAO;
import dao.LivroDAO;
import entidade.Assunto;
import entidade.Autor;
import entidade.Editora;
import entidade.Livro;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tela.autores.ListAutor;
import tela.assuntos.ListAssunto;
import tela.editoras.ListEditora;
import util.BibliotecaUtil;
import util.LoggerUtil;

/**
 *
 * @author gusteinhoefel
 */
public class IfrCadLivros extends javax.swing.JDialog {

    /**
     * Creates new form IfrCadCidades
     *
     * @param parent
     * @param modal
     */
    //private final Frame frame;
    private boolean check = false;
    private Livro livro = null;
    private final LivroDAO daoLivro = new LivroDAO();
    private int linhaAutor;
    private int linhaAssunto;

    public IfrCadLivros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Livros");
        carregaDados();
        livro = new Livro();

    }

    public IfrCadLivros(java.awt.Frame parent, boolean modal, Livro tLivro) {
        super(parent, modal);
        initComponents();
        setTitle("Alteração de Livros");
        setLivro(tLivro);
        carregaDados();
        livro = new Livro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDBook = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        checkEmprestimo = new javax.swing.JCheckBox();
        txtDateAquisicao = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####",'_');
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboClassLiteraria = new javax.swing.JComboBox<>();
        comboColecoes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAnoEdicao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEdicao = new javax.swing.JTextField();
        txtVolume = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNumTombo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCDD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCDU = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNumExemplares = new javax.swing.JTextField();
        txtSubtitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCutter = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodEditora = new javax.swing.JTextField();
        txtNomeEditora = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlbAutor = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtCodAutor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtDescAutor = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTlbAssunto = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        txtCodAssunto = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        txtDescAssunto = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFocusable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Código:");

        txtIDBook.setEditable(false);
        txtIDBook.setEnabled(false);
        txtIDBook.setFocusable(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Título da Obra:");

        txtTitulo.setBackground(new java.awt.Color(204, 204, 204));

        checkEmprestimo.setText("Não disponibilizar para empréstimo");
        checkEmprestimo.setFocusable(false);
        checkEmprestimo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Dt. Aquisição:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Class. literária:");

        comboClassLiteraria.setBackground(new java.awt.Color(204, 204, 204));

        comboColecoes.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Coleções:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Ano Edição:");

        txtAnoEdicao.setBackground(new java.awt.Color(204, 204, 204));
        txtAnoEdicao.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtAnoEdicao.setText("2019");
        txtAnoEdicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoEdicaoKeyTyped(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Edição");

        txtEdicao.setBackground(new java.awt.Color(204, 204, 204));
        txtEdicao.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        txtVolume.setBackground(new java.awt.Color(204, 204, 204));
        txtVolume.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolumeActionPerformed(evt);
            }
        });
        txtVolume.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVolumeKeyTyped(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Volume:");

        txtNumTombo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNumTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTomboActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("N° Tombo:");

        txtCDD.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("CDD:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("CUTTER:");

        txtCDU.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        txtIsbn.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnKeyTyped(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("ISBN:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("CDU:");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("N° Exemplares:");

        txtNumExemplares.setBackground(new java.awt.Color(204, 204, 204));
        txtNumExemplares.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNumExemplares.setText("1");
        txtNumExemplares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumExemplaresKeyTyped(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Subtítulo da Obra:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Editora:");

        txtCodEditora.setBackground(new java.awt.Color(204, 204, 204));
        txtCodEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodEditoraFocusLost(evt);
            }
        });
        txtCodEditora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodEditoraKeyTyped(evt);
            }
        });

        txtNomeEditora.setEditable(false);
        txtNomeEditora.setEnabled(false);
        txtNomeEditora.setFocusable(false);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357371_free-01.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setRequestFocusEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIDBook, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboClassLiteraria, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEdicao)
                                            .addComponent(txtNumExemplares)
                                            .addComponent(txtAnoEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCDD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCutter, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                                    .addComponent(txtCDU)))))
                                    .addComponent(txtNomeEditora)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumTombo, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(txtDateAquisicao, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEmprestimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboClassLiteraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtCodEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNumTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtAnoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtNumExemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtCDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(txtCDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCutter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informações", jPanel1);

        jTlbAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlbAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlbAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTlbAutor);
        if (jTlbAutor.getColumnModel().getColumnCount() > 0) {
            jTlbAutor.getColumnModel().getColumn(0).setResizable(false);
            jTlbAutor.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTlbAutor.getColumnModel().getColumn(1).setResizable(false);
            jTlbAutor.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        jLabel17.setText("Código:");

        txtCodAutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodAutorFocusLost(evt);
            }
        });
        txtCodAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodAutorKeyTyped(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357539_free-05.png"))); // NOI18N
        jButton3.setToolTipText("Adiconar Autor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtDescAutor.setEditable(false);
        txtDescAutor.setEnabled(false);
        txtDescAutor.setFocusable(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357371_free-01.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setRequestFocusEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357528_free-27.png"))); // NOI18N
        jButton5.setToolTipText("Remover Autor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel18.setText("Nome do Autor:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCodAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDescAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Autores", jPanel2);

        jLabel20.setText("Descrição do Assunto:");

        jTlbAssunto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlbAssunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlbAssuntoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTlbAssunto);
        if (jTlbAssunto.getColumnModel().getColumnCount() > 0) {
            jTlbAssunto.getColumnModel().getColumn(0).setResizable(false);
            jTlbAssunto.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTlbAssunto.getColumnModel().getColumn(1).setResizable(false);
            jTlbAssunto.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        jLabel22.setText("Código:");

        txtCodAssunto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodAssuntoFocusLost(evt);
            }
        });
        txtCodAssunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodAssuntoKeyTyped(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357371_free-01.png"))); // NOI18N
        jButton9.setFocusable(false);
        jButton9.setRequestFocusEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtDescAssunto.setEditable(false);
        txtDescAssunto.setEnabled(false);
        txtDescAssunto.setFocusable(false);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357539_free-05.png"))); // NOI18N
        jButton10.setToolTipText("Adiconar Assunto");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357528_free-27.png"))); // NOI18N
        jButton11.setToolTipText("Remover Assunto");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtCodAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDescAssunto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Assuntos", jPanel3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1480357534_free-05.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1479862814_Cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodEditoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodEditoraFocusLost
        if (!txtCodEditora.getText().trim().isEmpty()) {
            try {
                Editora ret = new EditoraDAO().consultarId(Integer.parseInt(txtCodEditora.getText().trim()));
                if (ret != null) {
                    setEditora(ret);

                } else {
                    JOptionPane.showMessageDialog(null, "Código da editora não localizado!\nfavor digite outro código", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtCodEditora.requestFocusInWindow();
                }
            } catch (HeadlessException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.log(IfrCadLivros.class, ex.getMessage());
            }
        }
    }//GEN-LAST:event_txtCodEditoraFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ListEditora lp = new ListEditora(null, true, this);
        lp.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTlbAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlbAutorMouseClicked
        linhaAutor = this.jTlbAutor.getSelectedRow();
    }//GEN-LAST:event_jTlbAutorMouseClicked

    private void txtCodAutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodAutorFocusLost
        if (!txtCodAutor.getText().trim().isEmpty()) {
            try {
                Autor ret = new AutorDAO().consultarId(Integer.parseInt(txtCodAutor.getText().trim()));
                if (ret != null) {
                    setAutores(ret);
                } else {
                    JOptionPane.showMessageDialog(null, "Código do autor não localizado!\nfavor digite outro código", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtCodAutor.setText("");
                    txtDescAutor.setText("");
                    txtCodAutor.requestFocusInWindow();
                }
            } catch (HeadlessException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.log(IfrCadLivros.class, ex.getMessage());
            }
        }
    }//GEN-LAST:event_txtCodAutorFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!txtCodAutor.getText().trim().isEmpty() && !txtDescAutor.getText().trim().isEmpty() ) {
            DefaultTableModel dtm = (DefaultTableModel) jTlbAutor.getModel();
            dtm.addRow(new Object[]{
                txtCodAutor.getText(),
                txtDescAutor.getText(),});
            txtCodAutor.setText("");
            txtDescAutor.setText("");
            txtCodAutor.requestFocusInWindow();
        } else {
            JOptionPane.showMessageDialog(null, "Primeiro deve-se pesquisar um autor", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ListAutor lp = new ListAutor(null, true, this);
        lp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTlbAutor.getModel();
        dtm.removeRow(linhaAutor);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTlbAssuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlbAssuntoMouseClicked
        linhaAssunto = this.jTlbAssunto.getSelectedRow();
    }//GEN-LAST:event_jTlbAssuntoMouseClicked

    private void txtCodAssuntoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodAssuntoFocusLost
        if (!txtCodAssunto.getText().trim().isEmpty()) {
            try {
                Assunto ret = new AssuntoDAO().consultarId(Integer.parseInt(txtCodAssunto.getText().trim()));
                if (ret != null) {

                    setAssuntos(ret);

                } else {
                    JOptionPane.showMessageDialog(null, "Código do assunto não localizado!\nfavor digite outro código", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtCodAssunto.setText("");
                    txtDescAssunto.setText("");
                    txtCodAssunto.requestFocusInWindow();
                }
            } catch (HeadlessException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.log(IfrCadLivros.class, ex.getMessage());
            }
        }
    }//GEN-LAST:event_txtCodAssuntoFocusLost

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ListAssunto lp = new ListAssunto(null, true, this);
        lp.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!txtCodAssunto.getText().trim().isEmpty() && !txtDescAssunto.getText().trim().isEmpty()) {
            DefaultTableModel dtm = (DefaultTableModel) jTlbAssunto.getModel();
            dtm.addRow(new Object[]{
                txtCodAssunto.getText(),
                txtDescAssunto.getText(),});
            txtCodAssunto.setText("");
            txtDescAssunto.setText("");
            txtCodAssunto.requestFocusInWindow();
        } else {
            JOptionPane.showMessageDialog(null, "Primeiro deve-se pesquisar um assunto", "Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTlbAssunto.getModel();
        dtm.removeRow(linhaAssunto);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtIDBook.getText().trim().equals("")) {
            salvar();
        } else {
            alterar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNumTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTomboActionPerformed

    private void txtVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolumeActionPerformed

    private void txtIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyTyped
        BibliotecaUtil.eventoSemCaracteres(evt);
    }//GEN-LAST:event_txtIsbnKeyTyped

    private void txtAnoEdicaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoEdicaoKeyTyped
        BibliotecaUtil.eventoSemCaracteres(evt);
    }//GEN-LAST:event_txtAnoEdicaoKeyTyped

    private void txtNumExemplaresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumExemplaresKeyTyped
        BibliotecaUtil.eventoSemCaracteres(evt);
    }//GEN-LAST:event_txtNumExemplaresKeyTyped

    private void txtVolumeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVolumeKeyTyped
        BibliotecaUtil.eventoSemCaracteres(evt);
    }//GEN-LAST:event_txtVolumeKeyTyped

    private void txtCodEditoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodEditoraKeyTyped
        BibliotecaUtil.eventoSemCaracteres(evt);
    }//GEN-LAST:event_txtCodEditoraKeyTyped

    private void txtCodAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodAutorKeyTyped
        BibliotecaUtil.eventoSemCaracteres(evt);
    }//GEN-LAST:event_txtCodAutorKeyTyped

    private void txtCodAssuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodAssuntoKeyTyped
        BibliotecaUtil.eventoSemCaracteres(evt);
    }//GEN-LAST:event_txtCodAssuntoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkEmprestimo;
    private javax.swing.JComboBox<String> comboClassLiteraria;
    private javax.swing.JComboBox<String> comboColecoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTlbAssunto;
    private javax.swing.JTable jTlbAutor;
    private javax.swing.JTextField txtAnoEdicao;
    private javax.swing.JTextField txtCDD;
    private javax.swing.JTextField txtCDU;
    private javax.swing.JTextField txtCodAssunto;
    private javax.swing.JTextField txtCodAutor;
    private javax.swing.JTextField txtCodEditora;
    private javax.swing.JTextField txtCutter;
    private com.toedter.calendar.JDateChooser txtDateAquisicao;
    private javax.swing.JTextField txtDescAssunto;
    private javax.swing.JTextField txtDescAutor;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtIDBook;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNomeEditora;
    private javax.swing.JTextField txtNumExemplares;
    private javax.swing.JTextField txtNumTombo;
    private javax.swing.JTextField txtSubtitulo;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables

    public void setEditora(Editora editora) {
        txtCodEditora.setText(String.valueOf(editora.getId()));
        txtNomeEditora.setText(editora.getDescricao());
    }

    public void setAutores(Autor autor) {
        txtCodAutor.setText(String.valueOf(autor.getId()));
        txtDescAutor.setText(autor.getNome());
    }

    public void setAssuntos(Assunto assunto) {
        txtCodAssunto.setText(String.valueOf(assunto.getId()));
        txtDescAssunto.setText(assunto.getDescricao());
    }

    private void salvar() {

        if (jTlbAutor.getRowCount() != 0 && jTlbAssunto.getRowCount() != 0
                && !txtTitulo.getText().trim().equals("") && !txtCodEditora.getText().trim().equals("")
                && txtDateAquisicao.getDate() != null && !txtAnoEdicao.getText().trim().equals("")
                && !txtNumExemplares.getText().trim().equals("") && !txtVolume.getText().trim().equals("")
                && !txtEdicao.getText().trim().equals("")) {
            try {
                for (int i = 0; i < jTlbAutor.getRowCount(); i++) {
                    Autor s = new Autor();
                    s.setId(Integer.parseInt(jTlbAutor.getValueAt(i, 0).toString()));
                    s.setNome(jTlbAutor.getValueAt(i, 1).toString());
                    livro.addAutor(s);
                }

                for (int i = 0; i < jTlbAssunto.getRowCount(); i++) {
                    Assunto s = new Assunto();
                    s.setId(Integer.parseInt(jTlbAssunto.getValueAt(i, 0).toString()));
                    s.setDescricao(jTlbAssunto.getValueAt(i, 1).toString());
                    livro.addAssunto(s);
                }

                for (int i = 0; i < Integer.parseInt(txtNumExemplares.getText().trim()); i++) {
                    livro.setTitulo(txtTitulo.getText().trim());
                    livro.setSubtitulo(txtSubtitulo.getText().trim());
                    livro.setIsbn(txtIsbn.getText().trim().trim());
                    livro.setVolume(Integer.parseInt(txtVolume.getText().trim()));
                    livro.setAnoEdicao(Integer.parseInt(txtAnoEdicao.getText().trim()));
                    livro.setEdicao(Integer.parseInt(txtEdicao.getText().trim()));
                    livro.setTombo(txtNumTombo.getText().trim());
                    livro.setCdu(txtCDU.getText().trim());
                    livro.setCdd(txtCDD.getText().trim());
                    livro.setCutter(txtCutter.getText().trim());
                    livro.setEditora(new EditoraDAO().consultarId(Integer.parseInt(txtCodEditora.getText().trim())));
                    livro.setClassLiteraria(new ClassLiterariaDAO().consultarId(Integer.parseInt(comboClassLiteraria.getSelectedItem().toString().substring(0, (comboClassLiteraria.getSelectedItem().toString().split("-").length)).trim())));
                    livro.setColecao(new ColecaoDAO().consultarId(Integer.parseInt(comboColecoes.getSelectedItem().toString().substring(0, comboColecoes.getSelectedItem().toString().split("-").length).trim())));
                    livro.setData_aquisicao(new java.sql.Date(txtDateAquisicao.getDate().getTime()));
                    livro.setStatus(checkEmprestimo.isSelected()?1:0);

                    daoLivro.salvar(livro);
                }
                JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (HeadlessException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(IfrCadLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            txtTitulo.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Favor verificar se todos os campos na cor cinza estão preenchidos!\nou se ha autores e assuntos adicionados!", "", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterar() {
        if (jTlbAutor.getRowCount() != 0 && jTlbAssunto.getRowCount() != 0
                && !txtTitulo.getText().trim().equals("") && !txtCodEditora.getText().trim().equals("")
                && txtDateAquisicao.getDate() != null && !txtAnoEdicao.getText().trim().equals("")
                && !txtNumExemplares.getText().trim().equals("")) {
            try {
                for (int i = 0; i < jTlbAutor.getRowCount(); i++) {
                    Autor s = new Autor();
                    s.setId(Integer.parseInt(jTlbAutor.getValueAt(i, 0).toString()));
                    s.setNome(jTlbAutor.getValueAt(i, 1).toString());
                    livro.addAutor(s);
                }

                for (int i = 0; i < jTlbAssunto.getRowCount(); i++) {
                    Assunto s = new Assunto();
                    s.setId(Integer.parseInt(jTlbAssunto.getValueAt(i, 0).toString()));
                    s.setDescricao(jTlbAssunto.getValueAt(i, 1).toString());
                    livro.addAssunto(s);
                }

                livro.setId(Integer.parseInt(txtIDBook.getText().trim()));
                livro.setTitulo(txtTitulo.getText().trim());
                livro.setSubtitulo(txtSubtitulo.getText().trim());
                livro.setIsbn(txtIsbn.getText().trim().trim());
                livro.setVolume(Integer.parseInt(txtVolume.getText().trim()));
                livro.setAnoEdicao(Integer.parseInt(txtAnoEdicao.getText().trim()));
                livro.setEdicao(Integer.parseInt(txtEdicao.getText().trim()));
                livro.setTombo(txtNumTombo.getText().trim());
                livro.setCdu(txtCDU.getText().trim());
                livro.setCdd(txtCDD.getText().trim());
                livro.setCutter(txtCutter.getText().trim());
                livro.setEditora(new EditoraDAO().consultarId(Integer.parseInt(txtCodEditora.getText().trim())));
                livro.setClassLiteraria(new ClassLiterariaDAO().consultarId(Integer.parseInt(comboClassLiteraria.getSelectedItem().toString().substring(0, (comboClassLiteraria.getSelectedItem().toString().split("-").length)).trim())));
                livro.setColecao(new ColecaoDAO().consultarId(Integer.parseInt(comboColecoes.getSelectedItem().toString().substring(0, comboColecoes.getSelectedItem().toString().split("-").length).trim())));
                livro.setData_aquisicao(new java.sql.Date(txtDateAquisicao.getDate().getTime()));
                livro.setStatus(checkEmprestimo.isSelected()?1:0);

                daoLivro.atualizar(livro);

                JOptionPane.showMessageDialog(null, "Livro atualizado com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (HeadlessException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.log(IfrCadLivros.class, ex.getMessage());
                Logger.getLogger(IfrCadLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            txtTitulo.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Favor verificar se todos os campos na cor cinza estão preenchidos!\nou se há autores e assuntos adicionados!", "", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregaDados() {
        try {
            ColecaoDAO adao = new ColecaoDAO();
            adao.consultarTodos().forEach((c) -> {
                comboColecoes.addItem((c.getId() + " - " + c.getDescricao()));
            });

            ClassLiterariaDAO dao = new ClassLiterariaDAO();
            dao.consultarTodos().forEach((c) -> {
                comboClassLiteraria.addItem((c.getId() + " - " + c.getDescricao()));
            });
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(IfrCadLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void enviaCod(String codId) {
        txtNumExemplares.setEditable(false);
        txtNumExemplares.setEnabled(false);
        txtNumExemplares.setRequestFocusEnabled(false);

        try {
            Livro l = daoLivro.consultarId(Integer.parseInt(codId));
            DefaultTableModel jtAutor = (DefaultTableModel) jTlbAutor.getModel();
            DefaultTableModel jtAssunto = (DefaultTableModel) jTlbAssunto.getModel();
            jtAutor.setNumRows(0);
            jtAssunto.setNumRows(0);
            txtIDBook.setText(String.valueOf(l.getId()));
            txtTitulo.setText(l.getTitulo());
            txtSubtitulo.setText(l.getSubtitulo());
            txtDateAquisicao.setDate(l.getData_aquisicao());
            txtAnoEdicao.setText(String.valueOf(l.getAnoEdicao()));
            txtIsbn.setText(l.getIsbn());
            txtEdicao.setText(String.valueOf(l.getEdicao()));
            txtVolume.setText(String.valueOf(l.getVolume()));
            txtNumTombo.setText(l.getTombo());
            txtCDD.setText(l.getCdd());
            txtCDU.setText(l.getCdu());
            txtCutter.setText(l.getCutter());
            comboClassLiteraria.setSelectedItem(l.getClassLiteraria().getId());
            comboColecoes.setSelectedItem(l.getColecao().getId());
            checkEmprestimo.setSelected((l.getStatus() != 0));
            txtCodEditora.setText(l.getEditora().getId().toString());
            txtNomeEditora.setText(l.getEditora().getDescricao());
            //busca autores
            l.getAutor().forEach((a) -> {
                jtAutor.addRow(new Object[]{
                    a.getId(),
                    a.getNome()
                });
            });

            //busca assuntos
            l.getAssunto().forEach((s) -> {
                jtAssunto.addRow(new Object[]{
                    s.getId(),
                    s.getDescricao()
                });
            });

            this.txtTitulo.requestFocusInWindow();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(IfrCadLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setLivro(Livro con) {
        txtNumExemplares.setEditable(false);
        txtNumExemplares.setEnabled(false);
        txtNumExemplares.setRequestFocusEnabled(false);

        try {
            ArrayList<Livro> l = daoLivro.listarbyId(String.valueOf(con.getId()));
            DefaultTableModel jtAutor = (DefaultTableModel) jTlbAutor.getModel();
            DefaultTableModel jtAssunto = (DefaultTableModel) jTlbAssunto.getModel();
            jtAutor.setNumRows(0);
            jtAssunto.setNumRows(0);
            txtIDBook.setText(String.valueOf(l.get(0).getId()));
            txtTitulo.setText(l.get(0).getTitulo());
            txtSubtitulo.setText(l.get(0).getSubtitulo());
            txtDateAquisicao.setDate(l.get(0).getData_aquisicao());
            txtAnoEdicao.setText(String.valueOf(l.get(0).getAnoEdicao()));
            txtIsbn.setText(l.get(0).getIsbn());
            txtEdicao.setText(String.valueOf(l.get(0).getEdicao()));
            txtVolume.setText(String.valueOf(l.get(0).getVolume()));
            txtNumTombo.setText(l.get(0).getTombo());
            txtCDD.setText(l.get(0).getCdd());
            txtCDU.setText(l.get(0).getCdu());
            txtCutter.setText(l.get(0).getCutter());
            comboClassLiteraria.setSelectedItem(l.get(0).getClassLiteraria().getId());
            comboColecoes.setSelectedItem(l.get(0).getColecao().getId());
            checkEmprestimo.setSelected((l.get(0).getStatus() != 0));
            txtCodEditora.setText(l.get(0).getEditora().getId().toString());
            txtNomeEditora.setText(l.get(0).getEditora().getDescricao());
            //busca autores
            l.get(0).getAutor().forEach((a) -> {
                jtAutor.addRow(new Object[]{
                    a.getId(),
                    a.getNome()
                });
            });

            //busca assuntos
            l.get(0).getAssunto().forEach((s) -> {
                jtAssunto.addRow(new Object[]{
                    s.getId(),
                    s.getDescricao()
                });
            });

            this.txtTitulo.requestFocusInWindow();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(IfrCadLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
